### ISSUE TITLE
画像up2

### ISSUE THREAD

**Issue by ghost** [heada13/hiranaga_prj#3]
![hiragana02](https://user-images.githubusercontent.com/49239713/97958839-698b6900-1df1-11eb-8f93-23dc82e2bf3e.png)

**Comment by heada13** [comment]
![97958839-698b6900-1df1-11eb-8f93-23dc82e2bf3e](https://user-images.githubusercontent.com/74914458/99976681-1a7c9680-2de7-11eb-982f-312ca39ea616.png)
